name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:  # token for octocat actions
    description: 'the access key to do things as atvenu'
    required: false
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
