name: 'Issue Checkbox Change Extractor'
description: 'Find the check box that changed in an edit and share it'
outputs:
  formatted-string: # id of output
    description: 'Formatted string version of the original line.'
  checkbox-changes:
    description: 'json object of the changes'
runs:
  using: 'node20'
  main: 'dist/index.js'
